name: github discord logger

on: [push]

jobs:
  discord-log:
    runs-on: ubuntu-latest
    steps:
      - name: send embed to discord
        run: |
          AUTHOR="${{ github.actor }}"
          AVATAR="https://github.com{AUTHOR}.png"
          MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          TIMESTAMP="${{ github.event.head_commit.timestamp }}"
          
          count_added=$(echo '${{ toJson(github.event.head_commit.added) }}' | jq 'length')
          count_modified=$(echo '${{ toJson(github.event.head_commit.modified) }}' | jq 'length')
          count_removed=$(echo '${{ toJson(github.event.head_commit.removed) }}' | jq 'length')

          title=$(echo "$MESSAGE" | head -n 1 | jq -aR .)
          desc=$(echo "$MESSAGE" | tail -n +2 | jq -aR .)

          if [ "$desc" != '""' ] && [ ! -z "$desc" ]; then
            desc_block="description:\n\`\`\`\n\${desc:1:-1}\n\`\`\`\n"
          else
            desc_block=""
          fi

          stats="**Статистика изменений:**\n🟢 Добавлено: \`$count_added\` файлов | 🟡 Изменено: \`$count_modified\` файлов | 🔴 Удалено: \`$count_removed\` файла"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": null,
                 "embeds": [
                   {
                     "title": '"$title"',
                     "description": "'"$desc_block$stats"'",
                     "url": "'"$COMMIT_URL"'",
                     "color": 3158064,
                     "fields": [
                       {
                         "name": "repository",
                         "value": "`'"$REPO"'`",
                         "inline": true
                       },
                       {
                         "name": "branch",
                         "value": "`'"$BRANCH"'`",
                         "inline": true
                       }
                     ],
                     "author": {
                       "name": "'"$AUTHOR"'",
                       "icon_url": "'"$AVATAR"'"
                     },
                     "timestamp": "'"$TIMESTAMP"'"
                   }
                 ],
                 "attachments": []
               }' \
               ${{ secrets.malasolka_ds_webhook }}
